version: '3'

services: 

  app:
    build: 
      context: go-app
    container_name: go-app
    networks: 
      - go-network

  nginx:
    build: 
      context: nginx
    container_name: nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d/
    networks: 
      - go-network
    ports: 
      - "8080:80" 
    depends_on:
      - app

networks: 
  go-network:
    driver: bridge      
